name: backen CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  packages: write
   
env:
  IMAGE_TAG: dev
  BRANCH_NAME: main
  SERVICE_NAME: backend-cicd
  COMPOSE_DIR: docker-compose.yml
  WORKDIR: ~/github_actions/backend-cicd

  REPO_SOURCE: docker-compose.yaml
  REPO_TARGET: /home/ubuntu/github_actions/backend-cicd

jobs:

  # builder:
  #   name: "Build & Push docker image"
  #   runs-on: ubuntu-latest
  #   steps:
    
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - uses: ./.github/workflows/composite/jib
  #       with:
  #         image_name: ${{ secrets.REGISTRY_ENDPOINT }}/${{ env.SERVICE_NAME }}:${{ env.IMAGE_TAG }} # ghcr.io/imadfaouzi | backend-cicd | dev ---- fix this
  #         service_name: ${{ env.SERVICE_NAME }}
  #         registry_host: ${{ secrets.REGISTRY_HOST }}
  #         registry_username: ${{ github.actor }}
  #         registry_password: ${{ secrets.GTHB_PAT }}


  deploy:
    name: "Deploy To Server"
    runs-on: ubuntu-latest
    # needs: [builder]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/deploy
        with:
          service_id: ${{ env.service_name }}
          workdir: ${{ env.WORKDIR }}
          compose_dir: ${{ env.COMPOSE_DIR }}

          repo_source:  ${{ env.REPO_SOURCE }}
          repo_target:  ${{ env.REPO_TARGET }}

          repository: ${{ github.repository }}
          ssh_key: ${{ secrets.CLOUD_MYSERVER_SSH_KEY }}
          ssh_host: ${{ secrets.CLOUD_MYSERVER_HOST }}
          ssh_user: ${{ secrets.CLOUD_MYSERVER_USER }}
          registry_host: ${{ secrets.REGISTRY_HOST }}
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GHCR_PAT }}

          